# Generated by Django 3.2.6 on 2021-09-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='Capegemini', max_length=100),
        ),
    ]
