# Generated by Django 3.2.6 on 2021-09-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employee_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='emp',
        ),
    ]
