# Generated by Django 3.2.6 on 2021-09-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_license_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='license',
            table='license',
        ),
    ]
