# Generated by Django 3.2.7 on 2021-09-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyuser',
            old_name='eamil',
            new_name='email',
        ),
    ]
